### ISSUE TITLE
Error during scrape with data on AWS EFS

### ISSUE THREAD

**Issue by fcastarede** [xperimental/nextcloud-exporter#102]
The left space on a volume on AWS EFS has "no limit", and the returned number by nextcloud is kind of `<freespace>9.2233720360673E+18</freespace>`

Error log:
`Error during scrape: can not parse server info: json: cannot unmarshal number 9.2233720360673e+18 into Go struct field Nextcloud.ocs.data.nextcloud.system of type int64`

**Comment by xperimental** [comment]
I know this has been quite a while and I also don't have any familiarity with EFS, but looking at the code of Nextcloud, there is a possibility for a storage backend to report "unlimited storage" which then results in `freespace` not being set (see [here](https://github.com/nextcloud/serverinfo/blob/v28.0.3/lib/SystemStatistics.php#L167-L176)).

I guess you're not using any "special EFS" configuration though, but just mount the EFS volume as a normal filesystem, so that Nextcloud does not know of its special properties ...
