### ISSUE TITLE
Credentials problem

### ISSUE THREAD

**Issue by urbaman** [xperimental/nextcloud-exporter#107]
Hi,

I have a problem with the exporter and credentials.

- I created a "monitoring" user for metrics
- I disabled TFA for the user, using group (the user is in the "monitoring" group)
- I can access Nextcloud with the user, without TFA
- Using the exporter with username/password, or with username/apppassword after having generated the app-password
- The exporter logs "Error during scrape: wrong credentials"
- Nextcloud version: Nextcloud Hub 7 (28.0.1)

Is there something else I am missing?

**Comment by urbaman** [comment]
Ok, solved.

I had to put the user in the "admin" group.
Now the user has no TFA ("monitoring" group) but has access to serverinfo ("admin" group).

Thank you.

**Comment by xperimental** [comment]
Since Nextcloud 22, the recommended way of authenticating the exporter to the Nextcloud instance is no longer a user-account but a token configured just for this purpose. See [token authentication](https://github.com/xperimental/nextcloud-exporter?tab=readme-ov-file#token-authentication) in the readme.
