### ISSUE TITLE
Metric for server response time

### ISSUE THREAD

**Issue by chapa** [xperimental/nextcloud-exporter#17]
Hi,

Would it be possible to have a metric for the time taken by the request to the nextcloud server ?
This would be handy, don't you think ?

I looked all the `go_*` metrics but it doesn't seem to be one that fits what I'm looking for

**Comment by xperimental** [comment]
The exporter currently does not contain such a metric as I have not deemed the response time from the Nextcloud server interesting enough to include it. The main reason for this is that the exporter will typically be deployed "next to" the actual Nextcloud server, so the response time the exporter gets will not be indicative of the performance an actual user will get, because the user's request will take a different route through networks and might include more steps such as further load-balancers or proxies.

Prometheus generates a `scrape_duration_seconds` metric for the exporter which will, due to the fact that the exporter currently does the request to Nextcloud synchronously, include the response time to Nextcloud. I don't recommend using this metric as an indicator for the Nextcloud server though as the same restrictions mentioned above also apply here just in a different way.

If you want to measure the performance of your Nextcloud deployment as experienced by the users I would recommend to measure either at the webserver itself or a load-balancer/proxy between the webserver and the user. That way you'll actually capture the performance of the requests issued by the users themselves and not some synthetic request.

The `go_*` metrics do not actually contain data about Nextcloud, but instead are runtime metrics of the exporter itself.

**Comment by chapa** [comment]
Thanks for your detailed answer !

I didn't know about `scrape_duration_seconds`, I think I'll use it for now since I don't need a high precision (just need an approximation to notice eventual drastic and fast increase).

But yeah if I ever need something more accurate I'll rather measure the webserver :+1:
