### ISSUE TITLE
Support for Raspberry Pi

### ISSUE THREAD

**Issue by PySualk** [xperimental/nextcloud-exporter#2]
Hey there,

I would like to use the nextcloud-exporter with raspbian ... 
Do you have any advice how to do that?

Thanks for your help.

**Comment by xperimental** [comment]
Hi,

The nextcloud-exporter should run fine on raspbian without any modifications, you just need to compile it for a different architecture as the processor in the Raspberry Pi uses a different one than the CPU in your computer.

Luckily cross-compiling is very simple in Go, you just need to set the `GOARCH` environment variable (and `GOOS` if you are not on linux) to the architecture you need. I have a script to do that in one of my [other projects](https://github.com/xperimental/netatmo-exporter/blob/master/build-arm.sh) because I use that one on a RPi myself. That script might just work for you if you have Go installed and are using Linux...

That said, I plan to provide pre-built binaries for different architectures for the next version which will happen soon.

Have a nice day! :sunny:

**Comment by PySualk** [comment]
Dear Robert,

thanks for your message. I tried using your script but it failed with the following error:
```
pi@raspberrypi:~/go/src/github.com/xperimental/nextcloud-exporter $ GOOS=linux GOARCH=arm go build -v -ldflags="-s -w" .
github.com/xperimental/nextcloud-exporter
# github.com/xperimental/nextcloud-exporter
./main.go:67: config.InfoURL.Hostname undefined (type *url.URL has no field or method Hostname)
```

I am a Go newbie so I have no idea what the problem is. Maybe there are some libraries missing on my system?

Thanks again,
Klaus

**Comment by PySualk** [comment]
I succeeded building the exporter with go 1.11 on another system :-) Raspbian has go 1.7 ... maybe this was the problem.
