### ISSUE TITLE
This problem

### ISSUE THREAD

**Issue by pijn-tech** [xperimental/nextcloud-exporter#23]
![image](https://user-images.githubusercontent.com/51449054/88119212-0b2ed780-cbc0-11ea-9cd9-f12e5298a56d.png)

**Comment by xperimental** [comment]
Don't exactly know what you are doing there, but the `nextcloud-exporter` file you are using there apparently is not the binary from this project. You can download the current release [here](https://github.com/xperimental/nextcloud-exporter/releases/tag/v0.3.0).

I'd appreciate it if you could elaborate on your issue in the original issue instead of creating new ones, so that we can make progress.

Duplicate of #22
