### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by olegsidokhmetov** [xperimental/nextcloud-exporter#26]
root@nextcloud:/tmp# go get github.com/xperimental/nextcloud-exporter

root@nextcloud:/tmp# nextcloud-exporter --help
nextcloud-exporter: command not found

What is problem?

**Comment by xperimental** [comment]
I'm sorry but the documentation is not up to date anymore regarding the usage of `go get` since the project was converted to make use of Go Modules. If you are not planning to make any changes to the exporter, then I recommend getting one of the pre-built binaries from [the latest release](https://github.com/xperimental/nextcloud-exporter/releases/latest) or using the [docker image](https://hub.docker.com/r/xperimental/nextcloud-exporter/).

If you indeed want to make changes to the source code then please just clone the repository like any other one to a directory of your choice (as $GOPATH does not matter anymore). If you have `make` installed then building the binary is as simple as calling that tool, otherwise a `go build` should build you a runnable binary.

I hope this is helpful for you.

**Comment by olegsidokhmetov** [comment]
I downloaded source file, installed, but don't understand what I should to do next?22 окт. 2020 г. 0:08 пользователь Robert Jacob <notifications@github.com> написал:
I'm sorry but the documentation is not up to date anymore regarding the usage of go get since the project was converted to make use of Go Modules. If you are not planning to make any changes to the exporter, then I recommend getting one of the pre-built binaries from the latest release or using the docker image.
If you indeed want to make changes to the source code then please just clone the repository like any other one to a directory of your choice (as $GOPATH does not matter anymore). If you have make installed then building the binary is as simple as calling that tool, otherwise a go build should build you a runnable binary.
I hope this is helpful for you.

**Comment by olegsidokhmetov** [comment]
> 
> 
> I'm sorry but the documentation is not up to date anymore regarding the usage of `go get` since the project was converted to make use of Go Modules. If you are not planning to make any changes to the exporter, then I recommend getting one of the pre-built binaries from [the latest release](https://github.com/xperimental/nextcloud-exporter/releases/latest) or using the [docker image](https://hub.docker.com/r/xperimental/nextcloud-exporter/).
> 
> If you indeed want to make changes to the source code then please just clone the repository like any other one to a directory of your choice (as $GOPATH does not matter anymore). If you have `make` installed then building the binary is as simple as calling that tool, otherwise a `go build` should build you a runnable binary.
> 
> I hope this is helpful for you.

Hello!!!

Do you have manual how to install nextcloud-exporter-0.3.0-amd64 step by step? I did no find information about this in internet O_0

**Comment by xperimental** [comment]
There's currently no step-by-step instruction for getting the exporter to run, at least not here. Most of the process should be quite straight-forward and many configuration options largely depend on how your Nextcloud server is set up and where the server monitoring the Nextcloud installation network-wise relative to the Nextcloud server.

The file on the release page is an executable that can be run directly, no installation needed, though you probably need something to keep it running indefinitely and restart it on system restart, similar to how you set up the Apache/nginx and Database for the Nextcloud instance. I have provided a simple service unit file for systemd-users. If you are running on a Debian-based distribution there's also a Debian-package that can be installed and will also install the systemd unit.

**Comment by olegsidokhmetov** [comment]
Hello! I installed service. ButI can get metrics from group syntax: nextcloud_shares_total{type="group"}

[https://ibb.co/MnjXyMw](url)

**Comment by xperimental** [comment]
I'm assuming, this is because you have multiple metrics that match this query, because other labels have changed. If you want the total number of shares across all exporters then you can sum it up: `sum(nextcloud_shares_total{type="group"})`

Be aware that this will only work properly if you only monitor a single instance. Otherwise you still have to filter your series or not aggregate by all labels.

Is the dashboard you are using a public one or did you build it yourself?

**Comment by olegsidokhmetov** [comment]
**Thank you very much for your answers!!!**

I downloaded this dashboard from Grafana official site and a little bit changed for me.

So, I input: sum(nextcloud_shares_total{type="group"}) but I am still have group user 0

[<a href="https://ibb.co/wByCKgR"><img src="https://i.ibb.co/wByCKgR/2020-10-30-8-47-42.png" alt="2020-10-30-8-47-42" border="0"></a>](url)

**Comment by xperimental** [comment]
Sorry, there is a misunderstanding. The `nextcloud_shares_total` lists the _number of shares by type_ not the groups/users. So it would show "1" if you share a file or directory with a group, not if you _have_ a group.

There's currently no metric for the number of groups, only for users, which is `nextcloud_users_total`.

**Comment by xperimental** [comment]
@olegsidokhmetov Is the issue solved?

**Comment by olegsidokhmetov** [comment]
> 
> 
> @olegsidokhmetov Is the issue solved?

I do not know. because I would like to have number of "Group", but if this option _does not have_, that I thins issue is solved.

**Comment by xperimental** [comment]
Unfortunately the information you need is not provided by Nextcloud's [serverinfo](https://github.com/nextcloud/serverinfo), so this exporter can also not create a metric for it. If the information should be provided in the future it is no problem to also include it here.

Closing this now, as nothing can currently be done.
